# Default values for api-tester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 1pro/api-tester
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

podLabels: {}

service:
  type: NodePort
  port: 80
  nodePort: 32221

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

envFrom:
  configMapRef: api-tester-2221-properties

# Additional volumes on the output Deployment definition.
volumes:
  - name: secret-datasource
    secret:
      secretName: api-tester-2221-postgresql

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: secret-datasource
    mountPath: /usr/src/myapp/datasource

nodeSelector:
  kubernetes.io/hostname: k8s-master

configmap:
  data:
    properties:
      spring_profiles_active: "dev"
      application_role: "ALL"
      postgresql_filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"

secret:
  data:
    postgresql:
      postgresql-info.yaml: |
        driver-class-name: "org.postgresql.Driver"
        url: "jdbc:postgresql://postgresql:5431"
        username: "dev"
        password: "dev123"