
service:
  nodePort: 32223

envFrom:
  configMapRef: api-tester-2223-properties

# Additional volumes on the output Deployment definition.
volumes:
  - name: secret-datasource
    secret:
      secretName: api-tester-2223-postgresql