
service:
  nodePort: 32222

envFrom:
  configMapRef: api-tester-2222-properties

# Additional volumes on the output Deployment definition.
volumes:
  - name: secret-datasource
    secret:
      secretName: api-tester-2222-postgresql