apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  version: 2.0.0
resources:
  - ../../base
patches:
  - path: configmap-properties.yaml
  - path: deployment-spec.yaml
  - path: deployment-ver.yaml
  - path: hpa.yaml
  - path: secret-postgresql.yaml
  - path: service.yaml