apiVersion: v1
kind: Secret
metadata:
  namespace: anotherclass-221
  name: api-tester-2223-postgresql
stringData:
  postgresql-info.yaml: |
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgresql:5431"
    username: "dev"
    password: "dev123"
